In [1]:
import torch 
print(torch . __version__)

2.9.1+cpu


Creating Tensor 

In [2]:
# Scalar
scalar=torch.tensor(7)
scalar

tensor(7)

In [3]:
#scalar Dimensional 
scalar.ndim

0

In [4]:
 #Tensor back as Int type
scalar.item()

7

In [5]:
#vector 
vector=torch.tensor([7,1])
vector

tensor([7, 1])

In [6]:
#Vector Ndim
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
#matrix 
MARTIX=torch.tensor([[7,8],[8,7]])
MARTIX

tensor([[7, 8],
        [8, 7]])

In [9]:
MARTIX.ndim 

2

In [10]:
MARTIX[0]

tensor([7, 8])

In [11]:
MARTIX[1]

tensor([8, 7])

In [12]:
MARTIX.shape

torch.Size([2, 2])

In [13]:
# Tensor
TENSOR=torch.tensor([[[1,2,3],
                     [1,4,5],
                     [7,8,9]]])
TENSOR 

tensor([[[1, 2, 3],
         [1, 4, 5],
         [7, 8, 9]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
TENSOR[0]

tensor([[1, 2, 3],
        [1, 4, 5],
        [7, 8, 9]])

In [17]:
TENSOR[0,0]

tensor([1, 2, 3])

## Random Tensors
Why random Tensors?
 
Random Tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and tehn adjust those reandom numbers to better represent the data.represent 


Start twith random numbers -> look at data-> update random numbers-> look at data -> update the random numbers 


In [18]:
#create a random tensors of size or shape(3,4)
random=torch.rand(3,4)
random 
random1=torch.rand(10,10)
random1

tensor([[0.4295, 0.3955, 0.8417, 0.6901, 0.8534, 0.7016, 0.0419, 0.1411, 0.2214,
         0.5225],
        [0.5159, 0.2035, 0.0462, 0.0657, 0.4551, 0.3032, 0.4839, 0.5603, 0.5398,
         0.4902],
        [0.5415, 0.9954, 0.0157, 0.7955, 0.3218, 0.4446, 0.5303, 0.3888, 0.3865,
         0.8849],
        [0.8166, 0.3571, 0.4345, 0.8023, 0.3233, 0.4945, 0.3757, 0.6683, 0.0719,
         0.6234],
        [0.9023, 0.7089, 0.2497, 0.5586, 0.5528, 0.3316, 0.9647, 0.7137, 0.0218,
         0.5985],
        [0.7529, 0.0590, 0.7849, 0.0946, 0.9900, 0.2059, 0.2348, 0.0282, 0.0465,
         0.4920],
        [0.1738, 0.9256, 0.9207, 0.2657, 0.1165, 0.5245, 0.1149, 0.1231, 0.3308,
         0.6119],
        [0.2188, 0.3238, 0.3021, 0.3190, 0.5845, 0.4268, 0.1617, 0.4554, 0.2728,
         0.3099],
        [0.4213, 0.0061, 0.1924, 0.5047, 0.1626, 0.9737, 0.7377, 0.0166, 0.7282,
         0.6998],
        [0.7048, 0.2753, 0.5591, 0.5686, 0.2441, 0.9261, 0.5322, 0.6051, 0.7402,
         0.2698]])

In [19]:
random.ndim

2

In [20]:
# create a random tensor with similar shape to an image tensor 
rando_image_size_tensor=torch.rand(size=(224,224,3))# height,width, Colour Channel  
rando_image_size_tensor.ndim, rando_image_size_tensor.shape

(3, torch.Size([224, 224, 3]))

In [21]:
Random=torch.rand(224,224)
Random 


tensor([[0.7387, 0.9462, 0.8361,  ..., 0.9972, 0.1439, 0.8872],
        [0.9272, 0.7877, 0.9994,  ..., 0.8084, 0.4627, 0.5887],
        [0.4361, 0.8315, 0.4309,  ..., 0.4455, 0.4713, 0.3413],
        ...,
        [0.4645, 0.4761, 0.0287,  ..., 0.1505, 0.7446, 0.6921],
        [0.1706, 0.1748, 0.1119,  ..., 0.4177, 0.6740, 0.2794],
        [0.7453, 0.2909, 0.2062,  ..., 0.3796, 0.6346, 0.3131]])

In [22]:
Random.ndim

2

In [23]:
Random.shape

torch.Size([224, 224])

In [24]:
 torch.rand((3,224,244))

tensor([[[0.8020, 0.3138, 0.0732,  ..., 0.3577, 0.4946, 0.4311],
         [0.6474, 0.3109, 0.4277,  ..., 0.1454, 0.3145, 0.1107],
         [0.5804, 0.2744, 0.1649,  ..., 0.9087, 0.4074, 0.7517],
         ...,
         [0.4844, 0.8046, 0.1937,  ..., 0.6182, 0.7950, 0.9191],
         [0.3934, 0.9519, 0.5564,  ..., 0.3841, 0.0274, 0.4634],
         [0.1027, 0.0582, 0.6274,  ..., 0.2498, 0.8767, 0.8003]],

        [[0.4326, 0.1036, 0.1396,  ..., 0.3924, 0.9374, 0.3755],
         [0.5790, 0.1065, 0.8839,  ..., 0.2659, 0.5831, 0.8692],
         [0.1540, 0.7514, 0.6502,  ..., 0.4867, 0.4019, 0.3001],
         ...,
         [0.8701, 0.1553, 0.1716,  ..., 0.9804, 0.3360, 0.4295],
         [0.6908, 0.0511, 0.9950,  ..., 0.1323, 0.8585, 0.3348],
         [0.3030, 0.5132, 0.0315,  ..., 0.8161, 0.7324, 0.7696]],

        [[0.2398, 0.4591, 0.1717,  ..., 0.2355, 0.8271, 0.6659],
         [0.0461, 0.0419, 0.3181,  ..., 0.2752, 0.1171, 0.5000],
         [0.9565, 0.6764, 0.3951,  ..., 0.7988, 0.8565, 0.

In [25]:
### Zero and Ones
Zero =torch.zeros(3,4)
print(Zero)
# 0 multipled with any tensor is becomes zeros 

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [26]:
#create a tensors of all ones
ones=torch.ones(3,4)
# it convert all the number into ones
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [27]:
### Creating a range of tensors and tensors-like 
#use torch.range()
# range as been replaced by arange 


In [28]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
one=torch.arange(start=0,end=10000,step=100)



In [30]:
#creating tensors like 


In [31]:
torch.zeros_like(one)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0])

In [32]:
## Tensor  data type 
float_32_tensor= torch.tensor ([3.0,6.0,9.0],
                               dtype=None,
                               device=None,# what device is you tensor on 
                               requires_grad=False) # whether or  not to track Gradients
float_32_tensor

tensor([3., 6., 9.])

In [33]:
## Note tensor data type is one of the 3 big errors you will run into PYtorch 
## Tensor not right datatype
## Tensor  not right shape
## Tensor  not on the right device 


In [34]:
# Converting float 32 into float 16
floar_16_tensor= float_32_tensor.type(torch.float16)

In [35]:
floar_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [36]:
float_32_tensor*floar_16_tensor

tensor([ 9., 36., 81.])

In [37]:
# interger 
int_32=torch.tensor([3,6,8],dtype=torch.int32)
int_32

tensor([3, 6, 8], dtype=torch.int32)

In [38]:
int_32*float_32_tensor

tensor([ 9., 36., 72.])

In [39]:
int_64=torch.tensor([3,6,8],dtype=torch.int64)
int_64

tensor([3, 6, 8])

In [40]:
int_64* float_32_tensor

tensor([ 9., 36., 72.])

In [41]:
int_long=torch.tensor([3,6,8],dtype=torch.long)
int_long

tensor([3, 6, 8])

In [42]:
float_32_tensor*int_long

tensor([ 9., 36., 72.])

In [43]:
### Getting information from tensor 
### Tensor not right datatype -> to do get datatype from a tensor can use tensor.dtype
### Tensor not right shape -> to get shape from a tensor  can use tensor.shape
### Tensor not on the right device-> to get device from a tensor, can use tensor. device 


In [44]:
some_tensor =torch.rand(3,4)
some_tensor

tensor([[0.9998, 0.7478, 0.2135, 0.9024],
        [0.1090, 0.3198, 0.3518, 0.6768],
        [0.1513, 0.0330, 0.0615, 0.2831]])

In [45]:
print(some_tensor)
print(f"Datatype of tensor:{some_tensor.dtype}")
print(f"shape of tensor:{some_tensor.shape}")
print(f"Devic of tensor:{some_tensor.device}")

tensor([[0.9998, 0.7478, 0.2135, 0.9024],
        [0.1090, 0.3198, 0.3518, 0.6768],
        [0.1513, 0.0330, 0.0615, 0.2831]])
Datatype of tensor:torch.float32
shape of tensor:torch.Size([3, 4])
Devic of tensor:cpu


In [46]:
### Manipulating Tensor 

# Tensor operation Include
# ADD
# sub
# Multiplicatio
# Division
# Matrix Multiplication


In [47]:
### create a tensor 
tensor =torch.tensor([1,2,3])
tensor + 100

tensor([101, 102, 103])

In [48]:
tensor*10

tensor([10, 20, 30])

In [49]:
tensor-10

tensor([-9, -8, -7])

In [50]:
tensor * tensor

tensor([1, 4, 9])

In [51]:
tensor/tensor

tensor([1., 1., 1.])

In [52]:
# Try out pytroch in-built function 
torch.mul(tensor,10)

tensor([10, 20, 30])

In [53]:
torch.add(tensor,10)

tensor([11, 12, 13])

In [54]:
torch.div(tensor,tensor)

tensor([1., 1., 1.])

In [55]:
torch.sub(tensor,10)

tensor([-9, -8, -7])

In [56]:
### Matrix multiplication 
## Two main ways of performing multiplication in neural and DL
## 1. Element wise Multiplication
## 2. Matrix Multiplication (dot Product) . _>
###

In [57]:
## 1. Element wise Multiplication
print(tensor,"*",tensor)
print(f"Equals:{tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals:tensor([1, 4, 9])


In [58]:
%%time
torch.matmul(tensor,tensor)

CPU times: total: 0 ns
Wall time: 566 μs


tensor(14)

In [59]:
##  One of the most commen error  in dl is shape error 
## There are two main rule that performing matrix multiplication needs to satisfy
## @ stand for multiplication 
## The inner dimension must match
#(3,2)@ (3,2) Will not work
#(3,2)@ (2,3) will work 

# The Resulting matrix has the shape of the "outer Dimensions"
# One of the most common error in deep learning 


In [60]:
# To fix the shape using Transpose

tensor.T # Stand for Transpose 


C:\Users\darsh\AppData\Local\Temp\ipykernel_3924\1402565077.py:3: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\TensorShape.cpp:4419.)
  tensor.T # Stand for Transpose


tensor([1, 2, 3])

In [61]:
# Finding the min max mean and sum


In [62]:
#Creating a tensor 
z= torch.arange(0,100,10)
z


tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [63]:
torch.min(z)

tensor(0)

In [64]:
torch.max(z)

tensor(90)

In [65]:
torch.mean(z.type(torch.float32))

tensor(45.)

In [66]:
# torch shape and dtype can be stored 
torch.sum(z)

tensor(450)

In [67]:
# Finding the position of min  and max
z.argmin() # -> return min val back from the matrix

tensor(0)

In [68]:
# Find the position  in tensor that has the maximum value with argmax()
z.argmax()

tensor(9)

In [69]:
## Reshpaing Stacking  and Squeezing 

# * Reshaping reshapes an input tensor to a defined shape
# View - return of an input  tensor of certainn shape but keep the same memory as orginial tensor 
# stack ->  Combine multiple tensors on top of each other(vstack) or side by side(hstack)
# Squeeze- remove all '1'  dimension  from a tensor 
# * Unsequee add a '1' dimension to a target tensor 
## Permute Return a view of the input with dimension permuted 




In [70]:
# Let's create a tensor 
import torch
z=torch.arange(1.,10.)
z,z.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [71]:
z_reshape=z.reshape(9,1)
z_reshape,z_reshape.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [72]:
#change the view 
x=z.view(1,9)
x,x.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [73]:
# changinf z change z (because a view of  a tensor share the same memory as the original )

In [74]:
# stack tensor on top of each other 
x_stacked=torch.stack([z,z,z,z],dim=1)
x_stacked

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [75]:
#torch .squeeze-> from all the singel dimension 
z_reshape.shape

torch.Size([9, 1])

In [76]:
z_reshape.squeeze()

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [77]:
z_reshape.squeeze().shape

torch.Size([9])

In [78]:
z_reshape.unsqueeze(dim=0)

tensor([[[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]])

In [79]:
# torch permute 
s=torch.rand(2,3,4)
s_permut=s.permute(2,0,1) # shif the axis 0->1 1->2 2->0
s_permut.shape

torch.Size([4, 2, 3])

In [81]:
# Selecting  data (Indexing)


#Indexing with Pytorch is similar to indexing with numpy

In [84]:
import torch 
z=torch.arange(1,10).reshape(1,3,3)
z, z.shape 

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [85]:
# let's index  on our new tensor 
z[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [87]:
# Let's Index on the middle bracket (dim=1)
z[0][0]

tensor([1, 2, 3])

In [94]:
#Let's Index on the most inner bracket (last Dimesnsion )
z[0][1][1]

tensor(5)

In [93]:
z[0][2][2]

tensor(9)

In [96]:
# you can also use ":" to select "all" of a target dimension 
x[:,0]

tensor([1.])

In [97]:
# Get all values of 0th and qst dimension but only index 1 of 2nd dimension 
z[:,:,1]

tensor([[2, 5, 8]])

In [99]:
# Get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimension 
z[:,1,1]

tensor([5])

In [101]:
# Get Index 0 of 0th and 1s dimension and all values of 2nd dimension 
z[0,0,:]

tensor([1, 2, 3])

In [104]:
#Index on z to return 9
print(z[0,2,2])
#index on  z to return 3,6,9
print(z[:,:,2])

tensor(9)
tensor([[3, 6, 9]])


In [106]:
# Numpy and Pytorch tensors
# Numpy is a popular scientific python numerical computing
# and because of this, pytorch has functionality to interact with it
# data in Numpy  want in pytorch tensor 'torch.from_numpy(ndarray) '
# Pytoech tensor-> Numpy-> torch.tensor.numpy()


In [ ]:
import torch 
import numpy as np 
array=np.arange(1,8)
print(array)
print(array.shape)
print(array.size)
tensor=torch.from_numpy(array).type(torch.float32)# waring: when converting from numpy -> pytorch  pytorch reflect numpy default  one 

print('tensor ')
print(f"Tensor size:{tensor.size}")
print(f"Tensor shape:{tensor.shape}")
print(f"Tensor {tensor.dtype}")

[1 2 3 4 5 6 7]
(7,)
7
tensor 
Tensor size:<built-in method size of Tensor object at 0x000001E3E4955540>
Tensor shape:torch.Size([7])
Tensor torch.float32
