In [2]:
import torch 
print(torch . __version__)

2.9.1+cpu


Creating Tensor 

In [3]:
# Scalar
scalar=torch.tensor(7)
scalar

tensor(7)

In [4]:
#scalar Dimensional 
scalar.ndim

0

In [5]:
 #Tensor back as Int type
scalar.item()

7

In [6]:
#vector 
vector=torch.tensor([7,1])
vector

tensor([7, 1])

In [7]:
#Vector Ndim
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
#matrix 
MARTIX=torch.tensor([[7,8],[8,7]])
MARTIX

tensor([[7, 8],
        [8, 7]])

In [10]:
MARTIX.ndim 

2

In [11]:
MARTIX[0]

tensor([7, 8])

In [12]:
MARTIX[1]

tensor([8, 7])

In [13]:
MARTIX.shape

torch.Size([2, 2])

In [14]:
# Tensor
TENSOR=torch.tensor([[[1,2,3],
                     [1,4,5],
                     [7,8,9]]])
TENSOR 

tensor([[[1, 2, 3],
         [1, 4, 5],
         [7, 8, 9]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape

torch.Size([1, 3, 3])

In [17]:
TENSOR[0]

tensor([[1, 2, 3],
        [1, 4, 5],
        [7, 8, 9]])

In [18]:
TENSOR[0,0]

tensor([1, 2, 3])

## Random Tensors
Why random Tensors?
 
Random Tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and tehn adjust those reandom numbers to better represent the data.represent 


Start twith random numbers -> look at data-> update random numbers-> look at data -> update the random numbers 


In [23]:
#create a random tensors of size or shape(3,4)
random=torch.rand(3,4)
random 
random1=torch.rand(10,10)
random1

tensor([[0.2702, 0.5420, 0.0878, 0.2365, 0.9721, 0.4381, 0.1778, 0.6576, 0.8611,
         0.8307],
        [0.6282, 0.6760, 0.6961, 0.7892, 0.8379, 0.8988, 0.3444, 0.1276, 0.5023,
         0.2483],
        [0.7167, 0.9952, 0.8042, 0.9886, 0.7195, 0.6134, 0.4845, 0.1965, 0.5180,
         0.3165],
        [0.8536, 0.8786, 0.3326, 0.4007, 0.3941, 0.0070, 0.1526, 0.1608, 0.1020,
         0.2346],
        [0.8891, 0.3786, 0.0421, 0.1350, 0.3389, 0.1397, 0.2063, 0.8215, 0.3552,
         0.1222],
        [0.1810, 0.5205, 0.4400, 0.1095, 0.1402, 0.1009, 0.6269, 0.5864, 0.5048,
         0.0355],
        [0.8242, 0.2803, 0.1720, 0.8353, 0.4152, 0.7401, 0.1195, 0.8153, 0.0621,
         0.2849],
        [0.8589, 0.5160, 0.2558, 0.0255, 0.3254, 0.2067, 0.7951, 0.9109, 0.5310,
         0.4168],
        [0.5576, 0.7061, 0.6052, 0.6468, 0.4638, 0.5870, 0.8408, 0.1537, 0.5454,
         0.4441],
        [0.4250, 0.3709, 0.0772, 0.9255, 0.2449, 0.6325, 0.7944, 0.7586, 0.2340,
         0.1667]])

In [21]:
random.ndim

2

1000