In [5]:
import torch 
print(torch . __version__)

2.9.1+cpu


Creating Tensor 

In [8]:
# Scalar
scalar=torch.tensor(7)
scalar

tensor(7)

In [ ]:
#scalar Dimensional 
scalar.ndim

0

In [12]:
 #Tensor back as Int type
scalar.item()

7

In [14]:
#vector 
vector=torch.tensor([7,1])
vector

tensor([7, 1])

In [ ]:
#Vector Ndim
vector.ndim

1

In [17]:
vector.shape

torch.Size([2])

In [19]:
#matrix 
MARTIX=torch.tensor([[7,8],[8,7]])
MARTIX

tensor([[7, 8],
        [8, 7]])

In [20]:
MARTIX.ndim 

2

In [21]:
MARTIX[0]

tensor([7, 8])

In [23]:
MARTIX[1]

tensor([8, 7])

In [25]:
MARTIX.shape

torch.Size([2, 2])

In [30]:
# Tensor
TENSOR=torch.tensor([[[1,2,3],
                     [1,4,5],
                     [7,8,9]]])
TENSOR 

tensor([[[1, 2, 3],
         [1, 4, 5],
         [7, 8, 9]]])

In [31]:
TENSOR.ndim

3

In [32]:
TENSOR.shape

torch.Size([1, 3, 3])

In [33]:
TENSOR[0]

tensor([[1, 2, 3],
        [1, 4, 5],
        [7, 8, 9]])

In [34]:
TENSOR[0,0]

tensor([1, 2, 3])