In [2]:
import torch 
print(torch . __version__)

2.9.1+cpu


Creating Tensor 

In [3]:
# Scalar
scalar=torch.tensor(7)
scalar

tensor(7)

In [4]:
#scalar Dimensional 
scalar.ndim

0

In [5]:
 #Tensor back as Int type
scalar.item()

7

In [6]:
#vector 
vector=torch.tensor([7,1])
vector

tensor([7, 1])

In [7]:
#Vector Ndim
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
#matrix 
MARTIX=torch.tensor([[7,8],[8,7]])
MARTIX

tensor([[7, 8],
        [8, 7]])

In [10]:
MARTIX.ndim 

2

In [11]:
MARTIX[0]

tensor([7, 8])

In [12]:
MARTIX[1]

tensor([8, 7])

In [13]:
MARTIX.shape

torch.Size([2, 2])

In [14]:
# Tensor
TENSOR=torch.tensor([[[1,2,3],
                     [1,4,5],
                     [7,8,9]]])
TENSOR 

tensor([[[1, 2, 3],
         [1, 4, 5],
         [7, 8, 9]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape

torch.Size([1, 3, 3])

In [17]:
TENSOR[0]

tensor([[1, 2, 3],
        [1, 4, 5],
        [7, 8, 9]])

In [18]:
TENSOR[0,0]

tensor([1, 2, 3])

## Random Tensors
Why random Tensors?
 
Random Tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and tehn adjust those reandom numbers to better represent the data.represent 


Start twith random numbers -> look at data-> update random numbers-> look at data -> update the random numbers 


In [23]:
#create a random tensors of size or shape(3,4)
random=torch.rand(3,4)
random 
random1=torch.rand(10,10)
random1

tensor([[0.2702, 0.5420, 0.0878, 0.2365, 0.9721, 0.4381, 0.1778, 0.6576, 0.8611,
         0.8307],
        [0.6282, 0.6760, 0.6961, 0.7892, 0.8379, 0.8988, 0.3444, 0.1276, 0.5023,
         0.2483],
        [0.7167, 0.9952, 0.8042, 0.9886, 0.7195, 0.6134, 0.4845, 0.1965, 0.5180,
         0.3165],
        [0.8536, 0.8786, 0.3326, 0.4007, 0.3941, 0.0070, 0.1526, 0.1608, 0.1020,
         0.2346],
        [0.8891, 0.3786, 0.0421, 0.1350, 0.3389, 0.1397, 0.2063, 0.8215, 0.3552,
         0.1222],
        [0.1810, 0.5205, 0.4400, 0.1095, 0.1402, 0.1009, 0.6269, 0.5864, 0.5048,
         0.0355],
        [0.8242, 0.2803, 0.1720, 0.8353, 0.4152, 0.7401, 0.1195, 0.8153, 0.0621,
         0.2849],
        [0.8589, 0.5160, 0.2558, 0.0255, 0.3254, 0.2067, 0.7951, 0.9109, 0.5310,
         0.4168],
        [0.5576, 0.7061, 0.6052, 0.6468, 0.4638, 0.5870, 0.8408, 0.1537, 0.5454,
         0.4441],
        [0.4250, 0.3709, 0.0772, 0.9255, 0.2449, 0.6325, 0.7944, 0.7586, 0.2340,
         0.1667]])

In [21]:
random.ndim

2

In [28]:
# create a random tensor with similar shape to an image tensor 
rando_image_size_tensor=torch.rand(size=(224,224,3))# height,width, Colour Channel  
rando_image_size_tensor.ndim, rando_image_size_tensor.shape

(3, torch.Size([224, 224, 3]))

In [29]:
Random=torch.rand(224,224)
Random 


tensor([[0.2541, 0.4244, 0.8912,  ..., 0.7723, 0.6274, 0.1960],
        [0.3685, 0.1737, 0.0275,  ..., 0.0088, 0.4427, 0.2998],
        [0.7206, 0.0934, 0.6225,  ..., 0.1381, 0.4877, 0.6267],
        ...,
        [0.8618, 0.2045, 0.0811,  ..., 0.8007, 0.9933, 0.4072],
        [0.3763, 0.4317, 0.1949,  ..., 0.5288, 0.2665, 0.4237],
        [0.5518, 0.1259, 0.9221,  ..., 0.4492, 0.9708, 0.5292]])

In [30]:
Random.ndim

2

In [31]:
Random.shape

torch.Size([224, 224])

In [33]:
 torch.rand((3,224,244))

tensor([[[0.7412, 0.1971, 0.5661,  ..., 0.5197, 0.1191, 0.6111],
         [0.8078, 0.7571, 0.3273,  ..., 0.5239, 0.8134, 0.2644],
         [0.4480, 0.5001, 0.4895,  ..., 0.9282, 0.3038, 0.9099],
         ...,
         [0.8471, 0.4206, 0.5528,  ..., 0.0783, 0.9704, 0.2264],
         [0.1196, 0.1685, 0.8879,  ..., 0.1125, 0.0830, 0.2379],
         [0.8895, 0.9797, 0.9499,  ..., 0.4405, 0.5753, 0.9534]],

        [[0.0247, 0.1275, 0.3468,  ..., 0.9181, 0.3832, 0.0363],
         [0.4089, 0.1466, 0.9192,  ..., 0.0361, 0.5675, 0.1596],
         [0.0665, 0.2677, 0.7789,  ..., 0.4084, 0.3134, 0.1500],
         ...,
         [0.8002, 0.1385, 0.7735,  ..., 0.1373, 0.1847, 0.2288],
         [0.7975, 0.2491, 0.7878,  ..., 0.6513, 0.0609, 0.5076],
         [0.8337, 0.6808, 0.2176,  ..., 0.2529, 0.4174, 0.7885]],

        [[0.5033, 0.1976, 0.8448,  ..., 0.8979, 0.3971, 0.8705],
         [0.8254, 0.1173, 0.8015,  ..., 0.7956, 0.4013, 0.8045],
         [0.2577, 0.0707, 0.0158,  ..., 0.6001, 0.5356, 0.

In [39]:
### Zero and Ones
Zero =torch.zeros(3,4)
print(Zero)
# 0 multipled with any tensor is becomes zeros 

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [41]:
#create a tensors of all ones
ones=torch.ones(3,4)
# it convert all the number into ones
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
### Creating a range of tensors and tensors-like 
#use torch.range()
# range as been replaced by arange 


In [44]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
one=torch.arange(start=0,end=10000,step=100)



In [51]:
#creating tensors like 


In [54]:
torch.zeros_like(one)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0])

In [ ]:
## Tensor  data type 
float_32_tensor= torch.tensor ([3.0,6.0,9.0],
                               dtype=None,
                               device=None,# what device is you tensor on 
                               requires_grad=False) # whether or  not to track Gradients
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
## Note tensor data type is one of the 3 big errors you will run into PYtorch 
## Tensor not right datatype
## Tensor  not right shape
## Tensor  not on the right device 


In [61]:
# Converting float 32 into float 16
floar_16_tensor= float_32_tensor.type(torch.float16)

In [62]:
floar_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [63]:
float_32_tensor*floar_16_tensor

tensor([ 9., 36., 81.])

In [65]:
# interger 
int_32=torch.tensor([3,6,8],dtype=torch.int32)
int_32

tensor([3, 6, 8], dtype=torch.int32)

In [66]:
int_32*float_32_tensor

tensor([ 9., 36., 72.])

In [67]:
int_64=torch.tensor([3,6,8],dtype=torch.int64)
int_64

tensor([3, 6, 8])

In [68]:
int_64* float_32_tensor

tensor([ 9., 36., 72.])

In [70]:
int_long=torch.tensor([3,6,8],dtype=torch.long)
int_long

tensor([3, 6, 8])

In [71]:
float_32_tensor*int_long

tensor([ 9., 36., 72.])

In [ ]:
### Getting information from tensor 
### Tensor not right datatype -> to do get datatype from a tensor can use tensor.dtype
### Tensor not right shape -> to get shape from a tensor  can use tensor.shape
### Tensor not on the right device-> to get device from a tensor, can use tensor. device 


In [72]:
some_tensor =torch.rand(3,4)
some_tensor

tensor([[0.9350, 0.9188, 0.2606, 0.4671],
        [0.3095, 0.0054, 0.2358, 0.7831],
        [0.5185, 1.0000, 0.5252, 0.4555]])

In [76]:
print(some_tensor)
print(f"Datatype of tensor:{some_tensor.dtype}")
print(f"shape of tensor:{some_tensor.shape}")
print(f"Devic of tensor:{some_tensor.device}")

tensor([[0.9350, 0.9188, 0.2606, 0.4671],
        [0.3095, 0.0054, 0.2358, 0.7831],
        [0.5185, 1.0000, 0.5252, 0.4555]])
Datatype of tensor:torch.float32
shape of tensor:torch.Size([3, 4])
Devic of tensor:cpu


In [81]:
### Manipulating Tensor 

# Tensor operation Include
# ADD
# sub
# Multiplicatio
# Division
# Matrix Multiplication


In [82]:
### create a tensor 
tensor =torch.tensor([1,2,3])
tensor + 100

tensor([101, 102, 103])

In [83]:
tensor*10

tensor([10, 20, 30])

In [84]:
tensor-10

tensor([-9, -8, -7])

In [85]:
tensor * tensor

tensor([1, 4, 9])

In [86]:
tensor/tensor

tensor([1., 1., 1.])

In [87]:
# Try out pytroch in-built function 
torch.mul(tensor,10)

tensor([10, 20, 30])

In [88]:
torch.add(tensor,10)

tensor([11, 12, 13])

In [90]:
torch.div(tensor,tensor)

tensor([1., 1., 1.])

In [91]:
torch.sub(tensor,10)

tensor([-9, -8, -7])

In [ ]:
### Matrix multiplication 
## Two main ways of performing multiplication in neural and DL
## 1. Element wise Multiplication
## 2. Matrix Multiplication 