In [1]:
import tensorflow as tf
print(tf.__version__)
import numpy as np 

2.20.0


In [2]:
tensor=tf.constant(4)
print(tensor)

tf.Tensor(4, shape=(), dtype=int32)


In [3]:
# Rank shape 
R1_tensor=tf.constant([2.0,3.0,4.0])
print(R1_tensor)

tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)


In [4]:
# Rank shape
from numpy import dtype, float32


R2_tensor=tf.constant([[1,2],
                      [3,4],
                      [5,6]],
                      dtype=tf.float32)
print(R2_tensor)

tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float32)


In [5]:
rank_3_tensor = tf.constant([
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9]],
  [[10, 11, 12, 13, 14],
   [15, 16, 17, 18, 19]],
  [[20, 21, 22, 23, 24],
   [25, 26, 27, 28, 29]],])

print(rank_3_tensor)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)


In [6]:
np.array(R2_tensor)

array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float32)

In [7]:
R2_tensor.numpy()


array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float32)

In [8]:
a=tf.constant([[1,2],
               [3,4]],dtype=float32)
b=tf.constant([[4,5],[8,8]],dtype=float32)
print("Add :", tf.add(a,b))

Add : tf.Tensor(
[[ 5.  7.]
 [11. 12.]], shape=(2, 2), dtype=float32)


In [9]:
print("Multi: ",tf.multiply(a,b))

Multi:  tf.Tensor(
[[ 4. 10.]
 [24. 32.]], shape=(2, 2), dtype=float32)


In [10]:
print("Multi: ",tf.divide(a,b))

Multi:  tf.Tensor(
[[0.25  0.4  ]
 [0.375 0.5  ]], shape=(2, 2), dtype=float32)


In [11]:
print("Multi: ",tf.matmul(a,b))

Multi:  tf.Tensor(
[[20. 21.]
 [44. 47.]], shape=(2, 2), dtype=float32)


In [12]:
# Find the largest number in array
print(tf.reduce_max(R2_tensor))

tf.Tensor(6.0, shape=(), dtype=float32)


In [13]:
print(tf.math.argmax(R2_tensor))

tf.Tensor([2 2], shape=(2,), dtype=int64)


In [14]:
print(tf.nn.softmax(R2_tensor))

tf.Tensor(
[[0.26894143 0.73105854]
 [0.26894143 0.73105854]
 [0.26894143 0.73105854]], shape=(3, 2), dtype=float32)


In [15]:
tf.convert_to_tensor([1,2,3])

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [16]:
rank_4_tensor= tf.zeros([1,2,3,4,5])


In [17]:
print("Type of every element:", rank_4_tensor.dtype)
print("Number of axes:", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along axis 0 of tensor:", rank_4_tensor.shape[0])
print("Elements along the last axis of tensor:", rank_4_tensor.shape[-1])
print("Total number of elements (3*2*4*5): ", tf.size(rank_4_tensor).numpy())

Type of every element: <dtype: 'float32'>
Number of axes: 5
Shape of tensor: (1, 2, 3, 4, 5)
Elements along axis 0 of tensor: 1
Elements along the last axis of tensor: 5
Total number of elements (3*2*4*5):  120


In [19]:
rank_4_tensor= tf.constant([1,2,3,4,5])


In [20]:
print("First:", rank_4_tensor[0].numpy())
print("Second:", rank_4_tensor[1].numpy())
print("Last:", rank_4_tensor[-1].numpy())

First: 1
Second: 2
Last: 5
